### ISSUE TITLE
Broken arrow rendering in focus mode

### ISSUE THREAD

**Issue by nickdiego** [Elv13/collision#21]
First of all, thanks for your great work in this component and AwesomeWM!

**About the issue:**
A wrong calculation is causing rendering of arrow shapes appears broken, as shown in the attached screenshot.
![awesome-collision-arrow-bug](https://user-images.githubusercontent.com/1189757/29196224-020e8b24-7e01-11e7-9e1c-cd13db18945d.jpg)

**Comment by Elv13** [comment]
Fixed by #22
